# Generated by Django 4.2.30 on 2026-08-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_video', models.CharField(blank=True, max_length=500)),
                ('output_video', models.CharField(max_length=500)),
                ('peak_persons_detected', models.PositiveIntegerField(default=0)),
                ('total_visible_time', models.FloatField(blank=True, null=True)),
                ('selected_track_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonTrackStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('first_seen', models.FloatField()),
                ('last_seen', models.FloatField()),
                ('visible_duration', models.FloatField()),
                ('frames_seen', models.PositiveIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_stats', to='tracker.trackingreport')),
            ],
            options={
                'ordering': ['track_id'],
            },
        ),
    ]
