# Generated by Django 4.2.30 on 2026-08-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackFrameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.PositiveIntegerField()),
                ('timestamp', models.FloatField()),
                ('full_frame_url', models.CharField(blank=True, max_length=1000)),
                ('cropped_image_url', models.CharField(blank=True, max_length=1000)),
                ('thumbnail_url', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_events', to='tracker.persontrackstats')),
            ],
            options={
                'ordering': ['frame_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='trackframeevent',
            constraint=models.UniqueConstraint(fields=('track', 'frame_number'), name='unique_track_frame_event'),
        ),
    ]
