# Generated by Django 4.2.30 on 2026-08-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_trackframeevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontrackstats',
            name='separate_video_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
